### ISSUE TITLE
Unlink no work in windows.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/files#21]
Yii2 works:

https://github.com/yiisoft/yii2/blob/bdc29982fa72f6eb84db99c30bf45b472bb585dd/framework/helpers/BaseFileHelper.php#L423

Yii3 no works:

https://github.com/yiisoft/files/blob/720a3a03c414224d3fb598330e32cee2964ed076/src/FileHelper.php#L220

**Comment by samdark** [comment]
I've added tests for `unlink()` and these tests pass on Windows.

**Comment by samdark** [comment]
There should be a special case...

**Comment by vjik** [comment]
> I've added tests for `unlink()` and these tests pass on Windows.

Don't work for read-only file. 

```php
chmod($filePath, 777);
FileHelper::unlink($filePath); // don't remove in windows
```

**Comment by samdark** [comment]
Exactly that issue. The test wasn't correct in file rotator. Fixed it: https://github.com/yiisoft/log-target-file/pull/13/commits/b4476995834c77f61cdb7d4586d7a01cfa1b2346.
